export const USER_PASSWORD_DONT_MATCH = "passwords do not match";
export const USER_CHANGE_OTHER_USER_PASSWORD = "you can’t change other peoples’ passwords";
export const USER_SHORT_PASSWORD = "the password must be at least 6 characters long";
export const USER_PASSWORD_INCLUDES_SPACES = "the password must not contain spaces";
export const USER_PASSWORD_CANT_BE_NULL = "password cannot be null";
export const USER_OLD_PASSWORD_DONT_MATCH = "Old password doesn’t match";
export const USER_WRONG_CREDENTIALS = "wrong credentials";
export const USER_USER_NOT_FOUND = "user with such username was not found";
export const USER_USER_CANT_BE_NULL = "User cannot be null";
export const USER_FIELDS_CANT_BE_NULL = "One or more fields are null";
export const USER_ROLES_CANT_BE_EMPTY = "Set of roles cannot be empty";
export const USER_NO_AUTH_HEADER = "No authorization header present";
export const USER_USER_DONT_HAVE_ADMIN_PRIVILEGES = "User doesn’t have admin privileges";
export const USER_SHORT_USERNAME = "the username must be at least 6 characters long";
export const USER_USERNAME_INCLUDES_SPACES = "the username must not contain spaces";
export const USER_INVALID_EMAIL_FORMAT = "invalid email format"